name: Format

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run spotless
      - run: mvn spotless:apply

      # Setup java 11
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.

      # Google Java Format
      - uses: axel-op/googlejavaformat-action@v3.1.0
        with:
          args: --replace --skip-javadoc-formatting --skip-sorting-imports --skip-reflowing-long-strings
          version: 1.8

